# Generated by Django 6.0 on 2026-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
