# Generated by Django 6.0 on 2026-01-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
