# Generated by Django 6.0 on 2026-02-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
