# Generated by Django 6.0 on 2026-02-09 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('Electricity', 'Electricity'), ('Plumbing', 'Plumbing'), ('Furniture', 'Furniture'), ('Cleaning', 'Cleaning'), ('Water', 'Water'), ('Internet', 'Internet'), ('Food', 'Food / Mess'), ('Security', 'Security'), ('Noise', 'Noise / Discipline'), ('Staff', 'Staff / Management'), ('Medical', 'Medical'), ('Other', 'Other')], max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('expected_resolution_time', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
