# Generated by Django 6.0 on 2026-01-17 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('complaint_category', models.CharField(choices=[('Electricity', 'Electricity'), ('Plumbing', 'Plumbing'), ('Furniture', 'Furniture'), ('Cleaning', 'Cleaning'), ('Water', 'Water'), ('Internet', 'Internet'), ('Food', 'Food / Mess'), ('Security', 'Security'), ('Noise', 'Noise / Discipline'), ('Staff', 'Staff / Management'), ('Medical', 'Medical'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
