# Generated by Django 6.0 on 2026-01-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaintlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority_locked',
            field=models.BooleanField(default=False),
        ),
    ]
