# Generated by Django 6.0 on 2026-01-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='cleared_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
