# Generated by Django 6.0 on 2026-02-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_cleared_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
    ]
