# Generated by Django 6.0 on 2026-02-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_alter_complaint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_proof',
            field=models.ImageField(blank=True, null=True, upload_to='resolutions/'),
        ),
    ]
