# Generated by Django 6.0 on 2026-02-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('Plumbing', 'Plumbing'), ('Furniture', 'Furniture'), ('Cleaning', 'Cleaning'), ('Water', 'Water'), ('Internet', 'Internet'), ('Food', 'Food / Mess'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
